### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by mattcurrycom** [anaynayak/aws-security-viz#28]
I was not able to use rake; and the instructions given didn't work for me.

**Comment by mattcurrycom** [comment]
disregard, I see now. However just a simple set of instructions would be easier.

**Comment by mattcurrycom** [comment]
Oddly enought I c

**Comment by anaynayak** [comment]
@mattcurrycom , thanks for trying this out. 

Quick question. Did the following instructions specified in the readme not work for you?

```
gem install aws_security_viz
aws_security_viz --help
```

I'm not sure where gem binaries are getting installed. Are you using rvm/rbenv or a different gemset ? 

I have fixed some of the issues with vagrant up failing due to bundler version.

**Comment by mattcurrycom** [comment]
Tyvm, it appears to be working now. I did a simple gem install and now it grabbed it. Thanks for the update.
